;; The 'nil' configuration applies to all modes.
((scheme-mode . ((indent-tabs-mode . nil)
                 (tab-width . 2)
                 (eval . (progn
                           (put 'do-times 'scheme-indent-function 1)
                           (put 'call-with-temporary-filepath 'scheme-indent-function 1)
                           (put 'call/errno* 'scheme-indent-function 1)
                           (put 'call-with-prompt 'scheme-indent-function 1)
                           (put 'with-continuation-mark 'scheme-indent-function 2)
                           (put 'call-with-immediate-continuation-mark 'scheme-indent-function 1)
                           (put 'call-with-lbst 'scheme-indent-function 2)
                           (put 'switch 'scheme-indent-function 1)
                           (put 'call-with-okvs-cursor 'scheme-indent-function 2)
                           (put 'okvs-parameterize 'scheme-indent-function 1)
                           (put 'okvs-search 'scheme-indent-function 2)
                           (put 'call-with-okvs-transaction 'scheme-indent-function 1)
                           (put 'with-cost-center 'scheme-indent-function 1)
                           (put 'with-future-ready 'scheme-indent-function 1)
                           (put 'module 'scheme-indent-function 1)
                           (put 'match 'scheme-indent-function 1)
                           (put 'call-with-lock 'scheme-indent-function 1)
                           (put 'call/errno 'scheme-indent-function 1)
                           (put 'call-with-fdb-transaction 'scheme-indent-function 1)
                           (put 'call-with-fdb 'scheme-indent-function 0)
                           (put 'with-mutex 'scheme-indent-function 1)
                           (put 'call-with-errno 'scheme-indent-function 1)
                           (put 'with-lock 'scheme-indent-function 1)
                           (put 'guard 'scheme-indent-function 1)
                           (put 'call-with-db-transaction 'scheme-indent-function 1)
                           )))))
