name: checks

on: push

env:
  GH_TOKEN: ${{ secrets.LETLOOP }}
  BRANCH: ${{ github.head_ref || github.ref_name }}
  
jobs:
  checks:
    name: checks
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt -qq install chezscheme chezscheme-dev uuid-dev liblz4-dev liburing* > /dev/null
      - run: gh repo clone letloop/cli -- --branch $BRANCH --depth 1 
      - run: cd cli && ./venv
      - run: cd cli && scheme --program letloop.scm compile letloop.scm && mv a.out ./local/bin/letloop
      - run: cd cli && ./venv $(pwd)/local/ letloop exec main.scm
      - run: cd cli && ./venv $(pwd)/local/ letloop compile main.scm && mv a.out main
      - run: cd cli && ./main
      - run: cd cli && ./venv $(pwd)/local/ make check
