name: checks

on: push

env:
  GH_TOKEN: ${{ github.token }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  checks:
    name: checks
    runs-on: ubuntu-22.04
    steps:
      - run: gh auth status
      - run: sudo apt -qq install chezscheme chezscheme-dev uuid-dev liblz4-dev liburing* > /dev/null
      - run: gh repo clone letloop/letloop -- --branch $BRANCH --depth 1
      - run: cd letloop && make
      - run: cd letloop && ./local/bin/letloop
      - run: cd letloop && LETLOOP_ROOT=$(pwd) make LETLOOP=$(pwd)/local/bin/letloop check
