name: checks

on: push

env:
  GH_TOKEN: ${{ secrets.LETLOOP }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  checks:
    name: checks
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt -qq install chezscheme chezscheme-dev uuid-dev liblz4-dev liburing* > /dev/null
      - run: gh repo clone letloop/cli -- --branch $BRANCH --depth 1
      - run: cd cli && make
      - run: cd cli && ./local/bin/letloop
      - run: cd cli && make LETLOOP=$(pwd)/local/bin/letloop check
