name: pre-release

on: workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.LETLOOP }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: ubuntu
            version: jammy
            arch: amd64
            flavor: cisco

          - distribution: alpine
            version: 3.18
            arch: amd64
            flavor: cisco

          - distribution: archlinux
            version: current
            arch: amd64
            flavor: cisco

          - distribution: amazonlinux
            version: current
            arch: amd64
            flavor: cisco

          - distribution: rockylinux
            version: 9
            arch: amd64
            flavor: cisco

          - distribution: fedora
            version: 38
            arch: amd64
            flavor: cisco

          - distribution: mint
            version: vera
            arch: amd64
            flavor: cisco

          - distribution: debian
            version: bookworm
            arch: amd64
            flavor: cisco

    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update --yes && sudo apt install --yes systemd-container qemu-user-static python3-lxml python3-requests
      - run: gh repo clone letloop/cli -- --branch $BRANCH --depth 1
      - run: cd cli && git fetch --tags
      - run: cd cli && LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local timeout 3600 ./local/bin/letloop-it.sh ${{ matrix.arch }} ${{ matrix.distribution }} ${{ matrix.version }} ${{ matrix.flavor }}
