name: release

on: workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.LETLOOP }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo clone letloop/letloop-cli -- --branch $BRANCH --depth 1
      - run: cd letloop-cli && git fetch --tags
      - run: cd letloop-cli && git tag --points-at HEAD
      - run: cd letloop-cli && echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: cd letloop-cli && gh release create --draft ${{ steps.version.outputs.TAG_NAME }}

  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - distribution: ubuntu
            version: jammy
            arch: amd64
            flavor: cisco

          - distribution: ubuntu
            version: jammy
            arch: amd64
            flavor: racket

          - distribution: alpine
            version: 3.17
            arch: amd64
            flavor: cisco

          - distribution: alpine
            version: 3.17
            arch: amd64
            flavor: racket

          - distribution: alpine
            version: 3.17
            arch: aarch64
            flavor: racket
          
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - run: gh repo clone letloop/letloop-cli -- --branch $BRANCH --depth 1
      - run: cd letloop-cli && git fetch --tags
      - run: cd letloop-cli && git tag --points-at HEAD
      - run: cd letloop-cli && LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh ${{ matrix.arch }} ${{ matrix.distribution }} ${{ matrix.version }} ${{ matrix.flavor }}
      - run: cd letloop-cli && sudo mv local/rootfs/${{ matrix.arch }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.flavor }}/bin/letloop /tmp/letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}
      - run: cd letloop-cli && gh release upload $(git tag --points-at HEAD) /tmp/letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}

