name: release

on: workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.LETLOOP }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo clone letloop/cli -- --branch $BRANCH --depth 1
      - run: cd cli && git fetch --tags
      - run: cd cli && gh release create --draft $(git tag --points-at HEAD)

  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - distribution: ubuntu
            version: jammy
            arch: amd64
            flavor: cisco

          - distribution: ubuntu
            version: jammy
            arch: amd64
            flavor: racket

          - distribution: ubuntu
            version: jammy
            arch: aarch64
            flavor: racket

          - distribution: ubuntu
            version: bionic
            arch: amd64
            flavor: cisco

          - distribution: ubuntu
            version: bionic
            arch: amd64
            flavor: racket

          - distribution: ubuntu
            version: bionic
            arch: aarch64
            flavor: racket

          - distribution: ubuntu
            version: focal
            arch: amd64
            flavor: cisco

          - distribution: ubuntu
            version: focal
            arch: amd64
            flavor: racket

          - distribution: ubuntu
            version: focal
            arch: aarch64
            flavor: racket

          - distribution: alpine
            version: 3.17
            arch: amd64
            flavor: cisco

          - distribution: alpine
            version: 3.17
            arch: amd64
            flavor: racket

          - distribution: alpine
            version: 3.17
            arch: aarch64
            flavor: racket

          - distribution: archlinux
            version: current
            arch: amd64
            flavor: cisco

          - distribution: archlinux
            version: current
            arch: amd64
            flavor: racket

          - distribution: archlinux
            version: current
            arch: aarch64
            flavor: racket

          - distribution: amazonlinux
            version: current
            arch: amd64
            flavor: cisco

          - distribution: amazonlinux
            version: current
            arch: amd64
            flavor: racket

          - distribution: amazonlinux
            version: current
            arch: aarch64
            flavor: racket

          - distribution: rockylinux
            version: 8
            arch: amd64
            flavor: cisco

          - distribution: rockylinux
            version: 8
            arch: amd64
            flavor: racket

          - distribution: rockylinux
            version: 8
            arch: aarch64
            flavor: racket
            
          - distribution: rockylinux
            version: 9
            arch: amd64
            flavor: cisco

          - distribution: rockylinux
            version: 9
            arch: amd64
            flavor: racket

          - distribution: rockylinux
            version: 9
            arch: aarch64
            flavor: racket

          - distribution: fedora
            version: 36
            arch: amd64
            flavor: cisco

          - distribution: fedora
            version: 36
            arch: amd64
            flavor: racket
          
          - distribution: fedora
            version: 37
            arch: amd64
            flavor: cisco

          - distribution: fedora
            version: 37
            arch: amd64
            flavor: racket

          - distribution: fedora
            version: Rawhide
            arch: amd64
            flavor: cisco

          - distribution: fedora
            version: Rawhide
            arch: amd64
            flavor: racket

    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - run: gh repo clone letloop/cli -- --branch $BRANCH --depth 1
      - run: cd cli && git fetch --tags
      - run: cd cli && git tag --points-at HEAD
      - run: cd cli && LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh ${{ matrix.arch }} ${{ matrix.distribution }} ${{ matrix.version }} ${{ matrix.flavor }}
      - run: cd cli && sudo mv local/rootfs/${{ matrix.arch }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.flavor }}/bin/letloop /tmp/letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}
      - run: cd cli && gh release upload $(git tag --points-at HEAD) /tmp/letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}

