name: release

on: workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.LETLOOP }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo clone letloop/letloop -- --branch $BRANCH --depth 1
      - run: cd letloop && git fetch --tags
      - run: cd letloop && gh release create --draft $(git tag --points-at HEAD)

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: ubuntu
            version: jammy
            arch: amd64
            flavor: cisco

          - distribution: ubuntu
            version: jammy
            arch: aarch64
            flavor: cisco

          - distribution: ubuntu
            version: focal
            arch: amd64
            flavor: cisco

          - distribution: ubuntu
            version: focal
            arch: aarch64
            flavor: cisco

          - distribution: mint
            version: vera
            arch: amd64
            flavor: racket

          - distribution: alpine
            version: 3.19
            arch: amd64
            flavor: cisco

          - distribution: alpine
            version: 3.19
            arch: aarch64
            flavor: cisco

          - distribution: alpine
            version: "3.20"
            arch: amd64
            flavor: cisco

          - distribution: alpine
            version: "3.20"
            arch: aarch64
            flavor: cisco
            
          - distribution: alpine
            version: edge
            arch: amd64
            flavor: cisco

          - distribution: alpine
            version: edge
            arch: aarch64
            flavor: cisco

          - distribution: archlinux
            version: current
            arch: amd64
            flavor: cisco

          - distribution: archlinux
            version: current
            arch: aarch64
            flavor: cisco

          # - distribution: amazonlinux
          #   version: 2
          #   arch: amd64
          #   flavor: cisco

          # - distribution: amazonlinux
          #   version: 2
          #   arch: aarch64
          #   flavor: cisco

          # - distribution: rockylinux
          #   version: 9
          #   arch: amd64
          #   flavor: cisco

          # - distribution: rockylinux
          #   version: 9
          #   arch: aarch64
          #   flavor: cisco

          - distribution: fedora
            version: 39
            arch: amd64
            flavor: cisco

          # - distribution: fedora
          #   version: 39
          #   arch: aarch64
          #   flavor: cisco

          - distribution: fedora
            version: 40
            arch: amd64
            flavor: cisco

          # - distribution: fedora
          #   version: 40
          #   arch: aarch64
          #   flavor: cisco

          - distribution: debian
            version: bookworm
            arch: amd64
            flavor: cisco

          - distribution: debian
            version: bookworm
            arch: aarch64
            flavor: cisco
            
          - distribution: debian
            version: bullseye
            arch: amd64
            flavor: cisco

          - distribution: debian
            version: bullseye
            arch: aarch64
            flavor: cisco

    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - run: gh repo clone letloop/letloop -- --branch $BRANCH --depth 1
      - run: cd letloop && git fetch --tags
      - run: cd letloop && git tag --points-at HEAD

      # Compile, and check
      - run: cd letloop && LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local timeout 5400 ./local/bin/letloop-it.sh ${{ matrix.arch }} ${{ matrix.distribution }} ${{ matrix.version }} ${{ matrix.flavor }}

      # Publish the binary with a name that documents the deployment target
      - run: cd letloop && sudo mv local/rootfs/tmp/letloop.boot letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}.boot
      - run: cd letloop && gh release upload $(git tag --points-at HEAD) letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}.boot

      # Publish sha256 checksum
      - run: cd letloop && sha256sum letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}.boot > letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}.boot.sha256.txt
      - run: cd letloop && gh release upload $(git tag --points-at HEAD) letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}.boot.sha256.txt
