name: release

on: workflow_dispatch

env:
  GH_TOKEN: ${{ github.token }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo clone letloop/letloop -- --branch $BRANCH --depth 1
      - run: cd letloop && git fetch --tags
      - run: cd letloop && gh release create --draft $(git tag --points-at HEAD)

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: ubuntu
            version: jammy
            arch: amd64
            flavor: cisco

          - distribution: ubuntu
            version: jammy
            arch: amd64
            flavor: racket

          - distribution: ubuntu
            version: jammy
            arch: aarch64
            flavor: racket

          - distribution: ubuntu
            version: focal
            arch: amd64
            flavor: cisco

          - distribution: ubuntu
            version: focal
            arch: amd64
            flavor: racket

          - distribution: ubuntu
            version: focal
            arch: aarch64
            flavor: racket

          - distribution: mint
            version: vera
            arch: amd64
            flavor: cisco

          - distribution: mint
            version: vera
            arch: amd64
            flavor: racket

          - distribution: alpine
            version: 3.17
            arch: amd64
            flavor: cisco

          - distribution: alpine
            version: 3.17
            arch: amd64
            flavor: racket

          - distribution: alpine
            version: 3.17
            arch: aarch64
            flavor: racket

          - distribution: alpine
            version: 3.18
            arch: amd64
            flavor: cisco

          - distribution: alpine
            version: 3.18
            arch: amd64
            flavor: racket

          - distribution: alpine
            version: 3.18
            arch: aarch64
            flavor: racket

          - distribution: archlinux
            version: current
            arch: amd64
            flavor: cisco

          - distribution: archlinux
            version: current
            arch: amd64
            flavor: racket

          - distribution: archlinux
            version: current
            arch: aarch64
            flavor: racket

          - distribution: amazonlinux
            version: 2
            arch: amd64
            flavor: cisco

          - distribution: amazonlinux
            version: 2
            arch: amd64
            flavor: racket

          - distribution: amazonlinux
            version: current
            arch: aarch64
            flavor: racket

          - distribution: rockylinux
            version: 8
            arch: amd64
            flavor: cisco

          - distribution: rockylinux
            version: 8
            arch: amd64
            flavor: racket

          - distribution: rockylinux
            version: 8
            arch: aarch64
            flavor: racket

          - distribution: rockylinux
            version: 9
            arch: amd64
            flavor: cisco

          - distribution: rockylinux
            version: 9
            arch: amd64
            flavor: racket

          - distribution: rockylinux
            version: 9
            arch: aarch64
            flavor: racket

          - distribution: fedora
            version: 37
            arch: amd64
            flavor: cisco

          - distribution: fedora
            version: 37
            arch: amd64
            flavor: racket

          - distribution: fedora
            version: 37
            arch: aarch64
            flavor: racket

          - distribution: fedora
            version: 38
            arch: amd64
            flavor: cisco

          - distribution: fedora
            version: 38
            arch: amd64
            flavor: racket

          - distribution: fedora
            version: 38
            arch: aarch64
            flavor: racket

          - distribution: debian
            version: bookworm
            arch: amd64
            flavor: cisco

          - distribution: debian
            version: bookworm
            arch: amd64
            flavor: racket

          - distribution: debian
            version: bookworm
            arch: aarch64
            flavor: racket

    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - run: gh repo clone letloop/letloop -- --branch $BRANCH --depth 1
      - run: cd letloop && git fetch --tags
      - run: cd letloop && git tag --points-at HEAD

      # Compile, and check
      - run: cd letloop && LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh ${{ matrix.arch }} ${{ matrix.distribution }} ${{ matrix.version }} ${{ matrix.flavor }}

      # Publish the binary with a name that documents the deployment target
      - run: cd letloop && sudo mv local/rootfs/${{ matrix.arch }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.flavor }}/usr/local/bin/letloop letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}
      - run: cd letloop && gh release upload $(git tag --points-at HEAD) letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}

      # Publish sha256 checksum
      - run: cd letloop && sha256sum letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }} > letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}.sha256
      - run: cd letloop && gh release upload $(git tag --points-at HEAD) letloop.${{ matrix.flavor }}-${{ matrix.distribution }}-${{ matrix.version }}-${{ matrix.arch }}.sha256
