name: release

on: workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.LETLOOP }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release create --draft ${{ steps.version.outputs.TAG_NAME }}

  amd64-ubuntu-jammy-cisco:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 ubuntu jammy cisco
      - run: sudo mv local/rootfs/amd64-ubuntu-jammy-cisco/bin/letloop letloop.amd64-ubuntu-jammy-cisco
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} letloop.amd64-ubuntu-jammy-cisco

  amd64-ubuntu-jammy-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 ubuntu jammy racket
      - run: sudo mv local/rootfs/amd64-ubuntu-jammy-racket/bin/letloop letloop.amd64-ubuntu-jammy-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} letloop.amd64-ubuntu-jammy-racket
        
  aarch64-ubuntu-jammy-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh aarch64 ubuntu jammy racket
      - run: sudo mv local/rootfs/aarch64-ubuntu-jammy-racket/bin/letloop letloop.aarch64-ubuntu-jammy-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} letloop.aarch64-ubuntu-jammy-racket

  amd64-ubuntu-focal-cisco:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 ubuntu focal cisco
      - run: sudo mv local/rootfs/amd64-ubuntu-focal-cisco/bin/letloop letloop.amd64-ubuntu-focal-cisco
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} letloop.amd64-ubuntu-focal-cisco

  amd64-ubuntu-bionic-cisco:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 ubuntu bionic cisco
      - run: sudo mv local/rootfs/amd64-ubuntu-bionic-cisco/bin/letloop letloop.amd64-ubuntu-bionic-cisco
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} letloop.amd64-ubuntu-bionic-cisco

  amd64-alpine-3_17-cisco:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 alpine 3.17 cisco
      - run: sudo mv local/rootfs/amd64-alpine-3.17-cisco/bin/letloop letloop.amd64-alpine-3.17-cisco
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} letloop.amd64-alpine-3.17-cisco

  aarch64-alpine-3_17-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh aarch64 alpine 3.17 racket
      - run: sudo mv local/rootfs/aarch64-alpine-3.17-racket/bin/letloop letloop.aarch64-alpine-3.17-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} letloop.aarch64-alpine-3.17-racket
  
  amd64-archlinux-current-cisco:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 archlinux current cisco
      - run: sudo mv local/rootfs/amd64-archlinux-current-cisco/bin/letloop letloop.amd64-archlinux-current-cisco
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} letloop.amd64-archlinux-current-cisco

  amd64-archlinux-current-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 archlinux current racket
      - run: sudo mv local/rootfs/amd64-archlinux-current-racket/bin/letloop letloop.amd64-archlinux-current-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} letloop.amd64-archlinux-current-racket

  amd64-amazonlinux-current-cisco:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 amazonlinux current cisco
      - run: sudo mv local/rootfs/amd64-amazonlinux-current-cisco/bin/letloop /tmp/letloop.amd64-amazonlinux-current-cisco
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} /tmp/letloop.amd64-amazonlinux-current-cisco

  amd64-amazonlinux-current-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 amazonlinux current racket
      - run: sudo mv local/rootfs/amd64-amazonlinux-current-racket/bin/letloop /tmp/letloop.amd64-amazonlinux-current-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} /tmp/letloop.amd64-amazonlinux-current-racket

  aarch64-amazonlinux-current-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh aarch64 amazonlinux current racket
      - run: sudo mv local/rootfs/aarch64-amazonlinux-current-racket/bin/letloop /tmp/letloop.aarch64-amazonlinux-current-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} /tmp/letloop.aarch64-amazonlinux-current-racket

  amd64-fedora-rawhide-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 fedora Rawhide racket
      - run: sudo mv local/rootfs/amd64-fedora-rawhide-racket/bin/letloop /tmp/letloop.amd64-fedora-rawhide-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} /tmp/letloop.amd64-fedora-rawhide-racket

  aarch64-fedora-rawhide-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh aarch64 fedora Rawhide racket
      - run: sudo mv local/rootfs/aarch64-fedora-rawhide-racket/bin/letloop /tmp/letloop.aarch64-fedora-rawhide-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} /tmp/letloop.aarch64-fedora-rawhide-racket

  amd64-rockylinux-9-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh amd64 rockylinux 9 racket
      - run: sudo mv local/rootfs/amd64-rockylinux-9-racket/bin/letloop /tmp/letloop.amd64-rockylinux-9-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} /tmp/letloop.amd64-rockylinux-9-racket

  aarch64-rockylinux-9-racket:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - run: sudo apt install systemd-container qemu-user-static python3-lxml python3-requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --tags
      - run: git tag --points-at HEAD
      - run: LETLOOP_ROOT=$(pwd) LETLOOP_PREFIX=$(pwd)/local ./local/bin/letloop-it.sh aarch64 rockylinux 9 racket
      - run: sudo mv local/rootfs/aarch64-rockylinux-9-racket/bin/letloop /tmp/letloop.aarch64-rockylinux-9-racket
      - run: echo "TAG_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        id: version
      - run: gh release upload ${{ steps.version.outputs.TAG_NAME }} /tmp/letloop.aarch64-rockylinux-9-racket
